name: Playwright and Java Tests

on:
  push:
    branches:
      - main  # or your preferred branch
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Ensure you are using the latest v3

      # Step 1: Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3  # Ensure you're using the latest v3
        with:
          distribution: 'temurin'  # Use Eclipse Temurin distribution (formerly AdoptOpenJDK)
          java-version: '17'  # Specify the Java version (e.g., 17 for modern LTS)

      - name: Verify Java version
        run: java -version  # Optional: Check installed Java version

      # Step 2: Set up Node.js after Java
      - name: Set up Node.js
        uses: actions/setup-node@v3  # Ensure you are using the latest v3
        with:
          node-version: '20.x'  # Specify Node.js version 20.x

      # Step 3: Install project dependencies and run Playwright tests
      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # Step 4: Start server in the background
      - name: Start the server
        run: |
          npm start &  # Run server in background
          echo $! > server.pid  # Save the process ID (PID) for later termination

      # Step 5: Run Playwright Tests
      - name: Run Playwright Tests
        run: npx playwright test --reporter=html

      # Step 6: Kill the background server after tests complete
      - name: Stop server
        run: |
          kill $(cat server.pid)  # Kill the server using the saved PID
          rm server.pid  # Clean up the PID file

      # Step 7: List and upload the test report
      - name: List report directory
        run: ls -R playwright-report  # List all files recursively in the report directory

      - name: Upload Playwright HTML Report
        if: always()  # Upload the report regardless of test outcomes
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: playwright-report
          path: playwright-report  # Folder where Playwright stores the HTML report