name: "Playwright and JFrog Integration"

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Install Playwright browsers
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # Step 5: Start the server
      - name: Start the server
        run: |
          npm start &  # Run server in background
          echo $! > server.pid  # Save the process ID (PID) for later termination

      # Step 6: Run Playwright Tests
      - name: Run Playwright Tests
        run: |
          set +e  # Allow script to continue even if tests fail
          npx playwright test --reporter=html
          echo "TEST_RESULT=$?" >> $GITHUB_ENV  # Store the exit code (0=pass, non-zero=fail)
        continue-on-error: true  # Don't fail the pipeline if tests fail

      # Step 7: Stop the server
      - name: Stop server
        run: |
          kill $(cat server.pid)  # Kill the server using the saved PID
          rm server.pid  # Clean up the PID file

      # Step 8: Upload Playwright HTML Report (always upload report)
      - name: Upload Playwright HTML Report
        if: always()  # Upload the report regardless of test outcomes
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

  build:
    runs-on: ubuntu-latest
    needs: test  # Ensure this job runs after the test job

    steps:
      # Step 9: Message step based on the test result
      - name: Check test result and report status
        run: |
          if [ "${{ env.TEST_RESULT }}" -eq 0 ]; then
            echo "Playwright tests passed, proceeding with the build."
          else
            echo "Playwright tests failed, skipping the build."
            exit 0  # Exit successfully but skip the rest of the steps
          fi

      # Step 10: Build the project only if the tests passed
      - name: Build Project
        if: ${{ env.TEST_RESULT == 0 }}  # Run only if tests passed
        run: npm run build

      # Step 11: Continue with JFrog integration only if tests passed
      - name: Setup JFrog CLI
        if: ${{ env.TEST_RESULT == 0 }}  # Run only if tests passed
        uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

      - name: Set CLI Config
        if: ${{ env.TEST_RESULT == 0 }}  # Run only if tests passed
        run: jf npm-config --global=true --repo-resolve=cgdemo-virtual --repo-deploy=cgdemo-virtual

      - name: Install Deps using JFrog CLI
        if: ${{ env.TEST_RESULT == 0 }}  # Run only if tests passed
        run: jf npm install

      - name: Archive Artifacts into TGZ with Timestamp
        if: ${{ env.TEST_RESULT == 0 }}  # Run only if tests passed
        run: |
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          tar -czf build_${TIMESTAMP}.tgz build/

      - name: Push Artifacts to JFrog
        if: ${{ env.TEST_RESULT == 0 }}  # Run only if tests passed
        run: jf rt u "build_${{ env.TIMESTAMP }}.tgz" "cgdemo-virtual/cg-artifacts/build_${{ env.TIMESTAMP }}.tgz"

      - name: Publish the npm package to JFrog Artifactory
        if: ${{ env.TEST_RESULT == 0 }}  # Run only if tests passed
        run: jf npm publish

      - name: Publish Build Info with JFrog CLI
        if: ${{ env.TEST_RESULT == 0 }}  # Run only if tests passed
        run: |
          jf rt build-collect-env
          jf rt build-add-git
          jf rt build-publish